# Generated by Django 2.2.4 on 2022-02-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20220209_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
