# Generated by Django 2.2.4 on 2022-02-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
